# fly.toml app configuration file generated for navlo-frontend on 2026-09-08T20:00:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'navlo-frontend'
primary_region = 'fra'

[build]
  [build.args]
    VITE_API_BASE = "https://navlo-backend.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
